# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0815f143724db60265524531aad40302f4628e7e48c688dd89e2bb7117b182d9852997925c8dc4603e955c7cb4bf0651fd6de569f5e7a5a20f16d37abb198d38

test:
  secret_key_base: 7cbc58207ced7729cbeb456b14ef53a562136dc7d3e4d48b579e8d074ac758dbba488c0366a3adc449a82050a8efb4141e75c55d58c752f5408e7dfb742aa4d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
